version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: anands
      POSTGRES_PASSWORD: 87szLCJM
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: bridge
